### ISSUE TITLE
Crash when certain players are in the lobby

### ISSUE THREAD

**Issue by paltapica** [EnhancedNetwork/BetterAmongUs-Public#5]
![BAUFreeze](https://github.com/user-attachments/assets/d7289203-3ac9-42ea-b400-43a9fe0c9c16)

I was just in a lobby, not the host and all i know is that the player was marked as a known cheater, had no friend code and the attached is all i can give you, the game was freezing, accepted no input (so no log dump) and the BAU console was on a loop as shown in the attachment.
This was the second time i had joined that lobby with that player present and BAU crashed both times.

Hope this helps in some way.

**Comment by D1GQ** [comment]
Fixed

**Comment by paltapica** [comment]
This one is still happening from time to time, FYI.
